In [19]:
import h2o
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

In [4]:
h2o.init(nthreads=-1)

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; OpenJDK 64-Bit Server VM (build 11.0.6+8-b765.1, mixed mode)
  Starting server from C:\Users\e01703\AppData\Local\Continuum\anaconda3\lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\e01703\AppData\Local\Temp\tmprq6fehqj
  JVM stdout: C:\Users\e01703\AppData\Local\Temp\tmprq6fehqj\h2o_E01703_started_from_python.out
  JVM stderr: C:\Users\e01703\AppData\Local\Temp\tmprq6fehqj\h2o_E01703_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Asia/Kolkata
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.30.0.3
H2O_cluster_version_age:    16 days
H2O_cluster_name:           H2O_from_python_E01703_2uzwvb
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.971 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.3 final
--------------------------  ---------------------------------------------------------

In [5]:
df = h2o.import_file('../datasets-provided/test.csv')
df.head()

Parse progress: |█████████████████████████████████████████████████████████| 100%

age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target
41,management,married,tertiary,no,5883,no,no,cellular,20,nov,182,2,-1,0,unknown,0
47,technician,married,secondary,no,1233,yes,no,unknown,11,sep,91,1,100,2,other,1
51,blue-collar,married,primary,no,5050,no,yes,unknown,16,jun,75,7,-1,0,unknown,0
54,retired,married,secondary,no,3671,no,no,unknown,11,jun,67,3,-1,0,unknown,0
31,blue-collar,married,secondary,no,1243,yes,no,unknown,21,may,32,1,-1,0,unknown,0
59,retired,married,primary,no,0,no,no,cellular,5,jun,493,2,-1,0,unknown,1
54,services,married,primary,no,8,yes,no,cellular,14,may,143,1,-1,0,unknown,0
56,blue-collar,married,primary,no,828,yes,no,cellular,14,may,214,1,349,1,failure,0
42,admin.,married,secondary,no,214,yes,no,unknown,28,may,21,24,-1,0,unknown,0
56,housemaid,married,tertiary,no,1922,yes,no,cellular,24,jul,247,2,-1,0,unknown,0

In [6]:
df.describe()

Rows:905
Cols:17

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target
type,int,enum,enum,enum,enum,int,enum,enum,enum,int,enum,int,int,int,int,enum,int
mins,19.0,,,,,-1206.0,,,,1.0,,5.0,1.0,-1.0,0.0,,0.0
mean,41.569060773480665,,,,,1535.9580110497238,,,,15.908287292817679,,253.57237569060774,2.904972375690608,39.31381215469613,0.5602209944751381,,0.11491712707182321
maxs,87.0,,,,,71188.0,,,,31.0,,3025.0,32.0,674.0,12.0,,1.0
sigma,10.622751386298551,,,,,3695.7431109372696,,,,8.130802070321973,,250.62752991107683,3.334226440434791,98.27350806014292,1.5582239563073312,,0.31909825030187716
zeros,0,,,,,73,,,,0,,0,0,0,742,,801
missing,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,41.0,management,married,tertiary,no,5883.0,no,no,cellular,20.0,nov,182.0,2.0,-1.0,0.0,unknown,0.0
1,47.0,technician,married,secondary,no,1233.0,yes,no,unknown,11.0,sep,91.0,1.0,100.0,2.0,other,1.0
2,51.0,blue-collar,married,primary,no,5050.0,no,yes,unknown,16.0,jun,75.0,7.0,-1.0,0.0,unknown,0.0
3,54.0,retired,married,secondary,no,3671.0,no,no,unknown,11.0,jun,67.0,3.0,-1.0,0.0,unknown,0.0
4,31.0,blue-collar,married,secondary,no,1243.0,yes,no,unknown,21.0,may,32.0,1.0,-1.0,0.0,unknown,0.0
5,59.0,retired,married,primary,no,0.0,no,no,cellular,5.0,jun,493.0,2.0,-1.0,0.0,unknown,1.0
6,54.0,services,married,primary,no,8.0,yes,no,cellular,14.0,may,143.0,1.0,-1.0,0.0,unknown,0.0
7,56.0,blue-collar,married,primary,no,828.0,yes,no,cellular,14.0,may,214.0,1.0,349.0,1.0,failure,0.0
8,42.0,admin.,married,secondary,no,214.0,yes,no,unknown,28.0,may,21.0,24.0,-1.0,0.0,unknown,0.0
9,56.0,housemaid,married,tertiary,no,1922.0,yes,no,cellular,24.0,jul,247.0,2.0,-1.0,0.0,unknown,0.0

In [7]:
df['target'] = df['target'].asfactor()

In [8]:
model = h2o.load_model('../trained-models/StackedEnsemble_BestOfFamily_AutoML_20200530_103520')

In [9]:
model

Model Details
=============
H2OStackedEnsembleEstimator :  Stacked Ensemble
Model Key:  StackedEnsemble_BestOfFamily_AutoML_20200530_103520

No model summary for this model

ModelMetricsBinomialGLM: stackedensemble
** Reported on train data. **

MSE: 0.015306773501104189
RMSE: 0.12372054599420497
LogLoss: 0.08484822194840541
Null degrees of freedom: 2696
Residual degrees of freedom: 2691
Null deviance: 1952.5781990496191
Residual deviance: 457.6713091896987
AIC: 469.6713091896987
AUC: 0.9998449221960078
AUCPR: 0.9988628875881416
Gini: 0.9996898443920157

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.28382726727916174:

               0      1   Error            Rate
0      0  2373.0    7.0  0.0029    (7.0/2380.0)
1      1     4.0  313.0  0.0126     (4.0/317.0)
2  Total  2377.0  320.0  0.0041   (11.0/2697.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold        value    idx
0                        max f1   0.283827     0.982732  210.0
1                        max f2   0.209625     0.986924  224.0
2                  max f0point5   0.403692     0.990291  197.0
3                  max accuracy   0.283827     0.995921  210.0
4                 max precision   0.958423     1.000000    0.0
5                    max recall   0.209625     1.000000  224.0
6               max specificity   0.958423     1.000000    0.0
7              max absolute_mcc   0.283827     0.980433  210.0
8    max min_per_class_accuracy   0.249296     0.993691  217.0
9   max mean_per_class_accuracy   0.209625     0.995588  224.0
10                      max tns   0.958423  2380.000000    0.0
11                      max fns   0.958423   315.000000    0.0
12                      max fps   0.031383  2380.000000  399.0
13                      max tps   0.209625   317.000000  224.0
14                      max tnr   0.958423     1.000000    0.0
15                      max fnr   0.958423     0.993691    0.0
16                      max fpr   0.031383     1.000000  399.0
17                      max tpr   0.209625     1.000000  224.0

Gains/Lift Table: Avg response rate: 11.75 %, avg score: 12.76 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.010011,0.932884,8.507886,8.507886,1.000000,0.946599,1.000000,0.946599,0.085174,0.085174,750.788644,750.788644
1,,2,0.020022,0.909499,8.507886,8.507886,1.000000,0.922422,1.000000,0.934510,0.085174,0.170347,750.788644,750.788644
2,,3,0.030033,0.871659,8.507886,8.507886,1.000000,0.893976,1.000000,0.920999,0.085174,0.255521,750.788644,750.788644
3,,4,0.040044,0.850177,8.507886,8.507886,1.000000,0.858408,1.000000,0.905351,0.085174,0.340694,750.788644,750.788644
4,,5,0.050056,0.809752,8.507886,8.507886,1.000000,0.832053,1.000000,0.890691,0.085174,0.425868,750.788644,750.788644
5,,6,0.100111,0.513656,8.507886,8.507886,1.000000,0.678495,1.000000,0.784593,0.425868,0.851735,750.788644,750.788644
6,,7,0.150167,0.122110,2.962005,6.659259,0.348148,0.270092,0.782716,0.613093,0.148265,1.000000,196.200491,565.925926
7,,8,0.200222,0.070958,0.000000,4.994444,0.000000,0.091184,0.587037,0.482616,0.000000,1.000000,-100.000000,399.444444
8,,9,0.299963,0.047654,0.000000,3.333745,0.000000,0.056482,0.391842,0.340922,0.000000,1.000000,-100.000000,233.374536
9,,10,0.400074,0.041196,0.000000,2.499537,0.000000,0.043822,0.293791,0.266578,0.000000,1.000000,-100.000000,149.953661
10,,11,0.500185,0.037945,0.000000,1.999259,0.000000,0.039553,0.234989,0.221140,0.000000,1.000000,-100.000000,99.925871
11,,12,0.599926,0.035834,0.000000,1.666873,0.000000,0.036890,0.195921,0.190507,0.000000,1.000000,-100.000000,66.687268
12,,13,0.700037,0.034151,0.000000,1.428496,0.000000,0.035055,0.167903,0.168276,0.000000,1.000000,-100.000000,42.849576
13,,14,0.799778,0.033339,0.000000,1.250348,0.000000,0.033642,0.146963,0.151486,0.000000,1.000000,-100.000000,25.034771
14,,15,0.899889,0.032213,0.000000,1.111248,0.000000,0.032889,0.130614,0.138292,0.000000,1.000000,-100.000000,11.124845
15,,16,1.000000,0.031261,0.000000,1.000000,0.000000,0.031713,0.117538,0.127622,0.000000,1.000000,-100.000000,0.000000

ModelMetricsBinomialGLM: stackedensemble
** Reported on validation data. **

MSE: 0.06769589921350617
RMSE: 0.2601843562044155
LogLoss: 0.2310787453364102
Null degrees of freedom: 918
Residual degrees of freedom: 913
Null deviance: 633.0135033572444
Residual deviance: 424.722733928322
AIC: 436.722733928322
AUC: 0.9126800976800977
AUCPR: 0.5297376568982881
Gini: 0.8253601953601954

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.19931599719891135:

              0      1   Error           Rate
0      0  761.0   58.0  0.0708   (58.0/819.0)
1      1   32.0   68.0    0.32   (32.0/100.0)
2  Total  793.0  126.0  0.0979   (90.0/919.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold       value    idx
0                        max f1   0.199316    0.601770  123.0
1                        max f2   0.090701    0.681063  188.0
2                  max f0point5   0.317548    0.587607   90.0
3                  max accuracy   0.317548    0.910773   90.0
4                 max precision   0.743093    0.750000   23.0
5                    max recall   0.039110    1.000000  330.0
6               max specificity   0.927554    0.998779    0.0
7              max absolute_mcc   0.148143    0.553715  140.0
8    max min_per_class_accuracy   0.085824    0.830000  196.0
9   max mean_per_class_accuracy   0.058443    0.838394  244.0
10                      max tns   0.927554  818.000000    0.0
11                      max fns   0.927554  100.000000    0.0
12                      max fps   0.031346  819.000000  399.0
13                      max tps   0.039110  100.000000  330.0
14                      max tnr   0.927554    0.998779    0.0
15                      max fnr   0.927554    1.000000    0.0
16                      max fpr   0.031346    1.000000  399.0
17                      max tpr   0.039110    1.000000  330.0

Gains/Lift Table: Avg response rate: 10.88 %, avg score: 11.13 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.010881,0.859912,5.514000,5.514000,0.600000,0.898113,0.600000,0.898113,0.06,0.06,451.400000,451.400000
1,,2,0.020675,0.762149,7.147778,6.287895,0.777778,0.811377,0.684211,0.857028,0.07,0.13,614.777778,528.789474
2,,3,0.030468,0.663127,5.105556,5.907857,0.555556,0.727246,0.642857,0.815312,0.05,0.18,410.555556,490.785714
3,,4,0.040261,0.588444,6.126667,5.961081,0.666667,0.616951,0.648649,0.767062,0.06,0.24,512.666667,496.108108
4,,5,0.050054,0.574523,6.126667,5.993478,0.666667,0.581597,0.652174,0.730775,0.06,0.30,512.666667,499.347826
5,,6,0.100109,0.316197,4.994565,5.494022,0.543478,0.430232,0.597826,0.580504,0.25,0.55,399.456522,449.402174
6,,7,0.150163,0.161952,3.196522,4.728188,0.347826,0.233040,0.514493,0.464682,0.16,0.71,219.652174,372.818841
7,,8,0.200218,0.098759,1.398478,3.895761,0.152174,0.125517,0.423913,0.379891,0.07,0.78,39.847826,289.576087
8,,9,0.300326,0.059085,1.198696,2.996739,0.130435,0.077187,0.326087,0.278990,0.12,0.90,19.869565,199.673913
9,,10,0.400435,0.047700,0.399565,2.347446,0.043478,0.052602,0.255435,0.222393,0.04,0.94,-60.043478,134.744565
10,,11,0.500544,0.041609,0.299674,1.937891,0.032609,0.044529,0.210870,0.186820,0.03,0.97,-70.032609,93.789130
11,,12,0.599565,0.038471,0.302967,1.667877,0.032967,0.039864,0.181488,0.162550,0.03,1.00,-69.703297,66.787659
12,,13,0.699674,0.036006,0.000000,1.429238,0.000000,0.037271,0.155521,0.144625,0.00,1.00,-100.000000,42.923795
13,,14,0.799782,0.034155,0.000000,1.250340,0.000000,0.035145,0.136054,0.130921,0.00,1.00,-100.000000,25.034014
14,,15,0.899891,0.033077,0.000000,1.111245,0.000000,0.033476,0.120919,0.120081,0.00,1.00,-100.000000,11.124547
15,,16,1.000000,0.031274,0.000000,1.000000,0.000000,0.032088,0.108814,0.111272,0.00,1.00,-100.000000,0.000000

ModelMetricsBinomialGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 0.07383605611501491
RMSE: 0.27172790823729337
LogLoss: 0.24963108224138064
Null degrees of freedom: 2696
Residual degrees of freedom: 2691
Null deviance: 1953.360638725976
Residual deviance: 1346.5100576100072
AIC: 1358.5100576100072
AUC: 0.899128515759616
AUCPR: 0.5546020350834459
Gini: 0.7982570315192321

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.16027062388352378:

               0      1   Error             Rate
0      0  2173.0  207.0   0.087   (207.0/2380.0)
1      1   108.0  209.0  0.3407    (108.0/317.0)
2  Total  2281.0  416.0  0.1168   (315.0/2697.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold        value    idx
0                        max f1   0.160271     0.570259  242.0
1                        max f2   0.074332     0.680905  308.0
2                  max f0point5   0.358521     0.562818  169.0
3                  max accuracy   0.506091     0.899889  116.0
4                 max precision   0.946446     1.000000    0.0
5                    max recall   0.032829     1.000000  392.0
6               max specificity   0.946446     1.000000    0.0
7              max absolute_mcc   0.160271     0.510336  242.0
8    max min_per_class_accuracy   0.079925     0.823950  302.0
9   max mean_per_class_accuracy   0.074332     0.832697  308.0
10                      max tns   0.946446  2380.000000    0.0
11                      max fns   0.946446   316.000000    0.0
12                      max fps   0.030133  2380.000000  399.0
13                      max tps   0.032829   317.000000  392.0
14                      max tnr   0.946446     1.000000    0.0
15                      max fnr   0.946446     0.996845    0.0
16                      max fpr   0.030133     1.000000  399.0
17                      max tpr   0.032829     1.000000  392.0

Gains/Lift Table: Avg response rate: 11.75 %, avg score: 11.75 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.010011,0.869118,6.932352,6.932352,0.814815,0.898162,0.814815,0.898162,0.069401,0.069401,593.235191,593.235191
1,,2,0.020022,0.791051,5.671924,6.302138,0.666667,0.832584,0.740741,0.865373,0.056782,0.126183,467.192429,530.213810
2,,3,0.030033,0.733414,5.041710,5.881996,0.592593,0.757313,0.691358,0.829353,0.050473,0.176656,404.171048,488.199556
3,,4,0.040044,0.671859,5.671924,5.829478,0.666667,0.701886,0.685185,0.797486,0.056782,0.233438,467.192429,482.947774
4,,5,0.050056,0.611518,4.726604,5.608903,0.555556,0.645657,0.659259,0.767120,0.047319,0.280757,372.660358,460.890291
5,,6,0.100111,0.350486,4.222433,4.915668,0.496296,0.472727,0.577778,0.619924,0.211356,0.492114,322.243253,391.566772
6,,7,0.150167,0.168381,3.025026,4.285454,0.355556,0.242735,0.503704,0.494194,0.151420,0.643533,202.502629,328.545391
7,,8,0.200222,0.108246,2.016684,3.718261,0.237037,0.136499,0.437037,0.404770,0.100946,0.744479,101.668419,271.826148
8,,9,0.299963,0.064745,1.233485,2.892050,0.144981,0.082436,0.339926,0.297591,0.123028,0.867508,23.348539,189.205040
9,,10,0.400074,0.049725,0.756257,2.357607,0.088889,0.056385,0.277108,0.237234,0.075710,0.943218,-24.374343,135.760708
10,,11,0.500185,0.042572,0.283596,1.942497,0.033333,0.045697,0.228317,0.198898,0.028391,0.971609,-71.640379,94.249742
11,,12,0.599926,0.039223,0.063256,1.630065,0.007435,0.040790,0.191595,0.172612,0.006309,0.977918,-93.674434,63.006477
12,,13,0.700037,0.036678,0.063021,1.405964,0.007407,0.037861,0.165254,0.153341,0.006309,0.984227,-93.697862,40.596428
13,,14,0.799778,0.034905,0.063256,1.238515,0.007435,0.035731,0.145573,0.138674,0.006309,0.990536,-93.674434,23.851476
14,,15,0.899889,0.033298,0.063021,1.107743,0.007407,0.034135,0.130202,0.127044,0.006309,0.996845,-93.697862,10.774294
15,,16,1.000000,0.029935,0.031511,1.000000,0.003704,0.032049,0.117538,0.117534,0.003155,1.000000,-96.848931,0.000000

In [10]:
y_pred = model.predict(df)

stackedensemble prediction progress: |████████████████████████████████████| 100%

In [14]:
y_pred

predict,p0,p1
0,0.96033,0.0396698
0,0.919572,0.0804283
0,0.964262,0.0357381
0,0.965764,0.0342355
0,0.964736,0.0352637
1,0.750747,0.249253
0,0.968227,0.031773
0,0.953124,0.0468761
0,0.968438,0.0315625
0,0.950358,0.0496419

In [31]:
print(confusion_matrix(df['target'].as_data_frame()['target'], y_pred['predict'].as_data_frame()['predict']))

[[753  48]
 [ 41  63]]

In [32]:
print(classification_report(df['target'].as_data_frame()['target'], y_pred['predict'].as_data_frame()['predict']))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94       801
           1       0.57      0.61      0.59       104

    accuracy                           0.90       905
   macro avg       0.76      0.77      0.77       905
weighted avg       0.90      0.90      0.90       905