In [1]:
import h2o
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
h2o.init(nthreads=-1)

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; OpenJDK 64-Bit Server VM (build 11.0.6+8-b765.1, mixed mode)
  Starting server from C:\Users\e01703\AppData\Local\Continuum\anaconda3\lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\e01703\AppData\Local\Temp\tmpo5kbjuht
  JVM stdout: C:\Users\e01703\AppData\Local\Temp\tmpo5kbjuht\h2o_E01703_started_from_python.out
  JVM stderr: C:\Users\e01703\AppData\Local\Temp\tmpo5kbjuht\h2o_E01703_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Asia/Kolkata
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.30.0.3
H2O_cluster_version_age:    16 days
H2O_cluster_name:           H2O_from_python_E01703_irgj0w
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.971 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.3 final
--------------------------  ---------------------------------------------------------

In [3]:
df = h2o.import_file('../datasets-provided/test.csv')
df.head()

Parse progress: |█████████████████████████████████████████████████████████| 100%

age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target
41,management,married,tertiary,no,5883,no,no,cellular,20,nov,182,2,-1,0,unknown,0
47,technician,married,secondary,no,1233,yes,no,unknown,11,sep,91,1,100,2,other,1
51,blue-collar,married,primary,no,5050,no,yes,unknown,16,jun,75,7,-1,0,unknown,0
54,retired,married,secondary,no,3671,no,no,unknown,11,jun,67,3,-1,0,unknown,0
31,blue-collar,married,secondary,no,1243,yes,no,unknown,21,may,32,1,-1,0,unknown,0
59,retired,married,primary,no,0,no,no,cellular,5,jun,493,2,-1,0,unknown,1
54,services,married,primary,no,8,yes,no,cellular,14,may,143,1,-1,0,unknown,0
56,blue-collar,married,primary,no,828,yes,no,cellular,14,may,214,1,349,1,failure,0
42,admin.,married,secondary,no,214,yes,no,unknown,28,may,21,24,-1,0,unknown,0
56,housemaid,married,tertiary,no,1922,yes,no,cellular,24,jul,247,2,-1,0,unknown,0

In [4]:
df.describe()

Rows:905
Cols:17

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target
type,int,enum,enum,enum,enum,int,enum,enum,enum,int,enum,int,int,int,int,enum,int
mins,19.0,,,,,-1206.0,,,,1.0,,5.0,1.0,-1.0,0.0,,0.0
mean,41.569060773480665,,,,,1535.9580110497238,,,,15.908287292817679,,253.57237569060774,2.904972375690608,39.31381215469613,0.5602209944751381,,0.11491712707182321
maxs,87.0,,,,,71188.0,,,,31.0,,3025.0,32.0,674.0,12.0,,1.0
sigma,10.622751386298551,,,,,3695.7431109372696,,,,8.130802070321973,,250.62752991107683,3.334226440434791,98.27350806014292,1.5582239563073312,,0.31909825030187716
zeros,0,,,,,73,,,,0,,0,0,0,742,,801
missing,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,41.0,management,married,tertiary,no,5883.0,no,no,cellular,20.0,nov,182.0,2.0,-1.0,0.0,unknown,0.0
1,47.0,technician,married,secondary,no,1233.0,yes,no,unknown,11.0,sep,91.0,1.0,100.0,2.0,other,1.0
2,51.0,blue-collar,married,primary,no,5050.0,no,yes,unknown,16.0,jun,75.0,7.0,-1.0,0.0,unknown,0.0
3,54.0,retired,married,secondary,no,3671.0,no,no,unknown,11.0,jun,67.0,3.0,-1.0,0.0,unknown,0.0
4,31.0,blue-collar,married,secondary,no,1243.0,yes,no,unknown,21.0,may,32.0,1.0,-1.0,0.0,unknown,0.0
5,59.0,retired,married,primary,no,0.0,no,no,cellular,5.0,jun,493.0,2.0,-1.0,0.0,unknown,1.0
6,54.0,services,married,primary,no,8.0,yes,no,cellular,14.0,may,143.0,1.0,-1.0,0.0,unknown,0.0
7,56.0,blue-collar,married,primary,no,828.0,yes,no,cellular,14.0,may,214.0,1.0,349.0,1.0,failure,0.0
8,42.0,admin.,married,secondary,no,214.0,yes,no,unknown,28.0,may,21.0,24.0,-1.0,0.0,unknown,0.0
9,56.0,housemaid,married,tertiary,no,1922.0,yes,no,cellular,24.0,jul,247.0,2.0,-1.0,0.0,unknown,0.0

In [5]:
df['target'] = df['target'].asfactor()

In [6]:
model = h2o.load_model('../trained-models/GBM_3_AutoML_20200530_103520')

In [7]:
model

Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_3_AutoML_20200530_103520


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,42.0,42.0,26495.0,8.0,8.0,8.0,23.0,78.0,45.357143

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 0.02313786027691328
RMSE: 0.1521113417103185
LogLoss: 0.0974422483553583
Mean Per-Class Error: 0.036154335551255246
AUC: 0.9930480078466719
AUCPR: 0.9698546523829054
Gini: 0.9860960156933438

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.3714105854408439:

               0      1   Error            Rate
0      0  2363.0   17.0  0.0071   (17.0/2380.0)
1      1    35.0  282.0  0.1104    (35.0/317.0)
2  Total  2398.0  299.0  0.0193   (52.0/2697.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold        value    idx
0                        max f1   0.371411     0.915584  164.0
1                        max f2   0.225599     0.922655  209.0
2                  max f0point5   0.455479     0.945848  144.0
3                  max accuracy   0.371411     0.980719  164.0
4                 max precision   0.971239     1.000000    0.0
5                    max recall   0.027831     1.000000  347.0
6               max specificity   0.971239     1.000000    0.0
7              max absolute_mcc   0.371411     0.905204  164.0
8    max min_per_class_accuracy   0.211221     0.962145  214.0
9   max mean_per_class_accuracy   0.211221     0.963846  214.0
10                      max tns   0.971239  2380.000000    0.0
11                      max fns   0.971239   316.000000    0.0
12                      max fps   0.004363  2380.000000  399.0
13                      max tps   0.027831   317.000000  347.0
14                      max tnr   0.971239     1.000000    0.0
15                      max fnr   0.971239     0.996845    0.0
16                      max fpr   0.004363     1.000000  399.0
17                      max tpr   0.027831     1.000000  347.0

Gains/Lift Table: Avg response rate: 11.75 %, avg score: 11.82 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.010011,0.908660,8.507886,8.507886,1.000000,0.937800,1.000000,0.937800,0.085174,0.085174,750.788644,750.788644
1,,2,0.020022,0.879682,8.507886,8.507886,1.000000,0.894780,1.000000,0.916290,0.085174,0.170347,750.788644,750.788644
2,,3,0.030033,0.852093,8.507886,8.507886,1.000000,0.866056,1.000000,0.899545,0.085174,0.255521,750.788644,750.788644
3,,4,0.040044,0.819786,8.507886,8.507886,1.000000,0.837074,1.000000,0.883927,0.085174,0.340694,750.788644,750.788644
4,,5,0.050056,0.795560,8.507886,8.507886,1.000000,0.806759,1.000000,0.868493,0.085174,0.425868,750.788644,750.788644
5,,6,0.100111,0.437745,8.066737,8.287312,0.948148,0.641090,0.974074,0.754792,0.403785,0.829653,706.673677,728.731160
6,,7,0.150167,0.191729,2.709919,6.428181,0.318519,0.292327,0.755556,0.600637,0.135647,0.965300,170.991938,542.818086
7,,8,0.200222,0.114991,0.252086,4.884157,0.029630,0.147655,0.574074,0.487392,0.012618,0.977918,-74.791448,388.415703
8,,9,0.299963,0.059629,0.126511,3.302196,0.014870,0.082738,0.388133,0.352840,0.012618,0.990536,-87.348868,230.219572
9,,10,0.400074,0.034688,0.063021,2.491652,0.007407,0.045403,0.292864,0.275910,0.006309,0.996845,-93.697862,149.165163
10,,11,0.500185,0.019899,0.031511,1.999259,0.003704,0.026295,0.234989,0.225950,0.003155,1.000000,-96.848931,99.925871
11,,12,0.599926,0.013422,0.000000,1.666873,0.000000,0.016341,0.195921,0.191101,0.000000,1.000000,-100.000000,66.687268
12,,13,0.700037,0.010665,0.000000,1.428496,0.000000,0.011889,0.167903,0.165473,0.000000,1.000000,-100.000000,42.849576
13,,14,0.799778,0.008769,0.000000,1.250348,0.000000,0.009682,0.146963,0.146044,0.000000,1.000000,-100.000000,25.034771
14,,15,0.899889,0.007162,0.000000,1.111248,0.000000,0.007913,0.130614,0.130677,0.000000,1.000000,-100.000000,11.124845
15,,16,1.000000,0.003998,0.000000,1.000000,0.000000,0.006269,0.117538,0.118222,0.000000,1.000000,-100.000000,0.000000

ModelMetricsBinomial: gbm
** Reported on validation data. **

MSE: 0.06904712817932163
RMSE: 0.26276820237487186
LogLoss: 0.22605672354555378
Mean Per-Class Error: 0.16087912087912093
AUC: 0.9111599511599512
AUCPR: 0.4970084931108656
Gini: 0.8223199023199024

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.29583183761599796:

              0      1   Error           Rate
0      0  769.0   50.0  0.0611   (50.0/819.0)
1      1   39.0   61.0    0.39   (39.0/100.0)
2  Total  808.0  111.0  0.0968   (89.0/919.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold       value    idx
0                        max f1   0.295832    0.578199  102.0
1                        max f2   0.098717    0.667752  190.0
2                  max f0point5   0.541125    0.583333   59.0
3                  max accuracy   0.541125    0.911861   59.0
4                 max precision   0.938707    1.000000    0.0
5                    max recall   0.020613    1.000000  324.0
6               max specificity   0.938707    1.000000    0.0
7              max absolute_mcc   0.295832    0.524575  102.0
8    max min_per_class_accuracy   0.092012    0.824176  200.0
9   max mean_per_class_accuracy   0.060794    0.839121  240.0
10                      max tns   0.938707  819.000000    0.0
11                      max fns   0.938707   99.000000    0.0
12                      max fps   0.004742  819.000000  399.0
13                      max tps   0.020613  100.000000  324.0
14                      max tnr   0.938707    1.000000    0.0
15                      max fnr   0.938707    0.990000    0.0
16                      max fpr   0.004742    1.000000  399.0
17                      max tpr   0.020613    1.000000  324.0

Gains/Lift Table: Avg response rate: 10.88 %, avg score: 11.17 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.010881,0.881465,4.595000,4.595000,0.500000,0.904422,0.500000,0.904422,0.05,0.05,359.500000,359.500000
1,,2,0.020675,0.837587,5.105556,4.836842,0.555556,0.858534,0.526316,0.882686,0.05,0.10,410.555556,383.684211
2,,3,0.030468,0.791096,6.126667,5.251429,0.666667,0.817699,0.571429,0.861797,0.06,0.16,512.666667,425.142857
3,,4,0.040261,0.727566,5.105556,5.215946,0.555556,0.750981,0.567568,0.834842,0.05,0.21,410.555556,421.594595
4,,5,0.050054,0.670004,8.168889,5.793696,0.888889,0.693629,0.630435,0.807213,0.08,0.29,716.888889,479.369565
5,,6,0.100109,0.370162,4.794783,5.294239,0.521739,0.519500,0.576087,0.663356,0.24,0.53,379.478261,429.423913
6,,7,0.150163,0.198635,2.397391,4.328623,0.260870,0.286820,0.471014,0.537844,0.12,0.65,139.739130,332.862319
7,,8,0.200218,0.137365,1.997826,3.745924,0.217391,0.164570,0.407609,0.444526,0.10,0.75,99.782609,274.592391
8,,9,0.300326,0.065623,1.398478,2.963442,0.152174,0.094145,0.322464,0.327732,0.14,0.89,39.847826,196.344203
9,,10,0.400435,0.036401,0.699239,2.397391,0.076087,0.049193,0.260870,0.258097,0.07,0.96,-30.076087,139.739130
10,,11,0.500544,0.020811,0.299674,1.977848,0.032609,0.028257,0.215217,0.212129,0.03,0.99,-70.032609,97.784783
11,,12,0.599565,0.014532,0.100989,1.667877,0.010989,0.017561,0.181488,0.179995,0.01,1.00,-89.901099,66.787659
12,,13,0.699674,0.011500,0.000000,1.429238,0.000000,0.013068,0.155521,0.156112,0.00,1.00,-100.000000,42.923795
13,,14,0.799782,0.009263,0.000000,1.250340,0.000000,0.010377,0.136054,0.137870,0.00,1.00,-100.000000,25.034014
14,,15,0.899891,0.007250,0.000000,1.111245,0.000000,0.008381,0.120919,0.123465,0.00,1.00,-100.000000,11.124547
15,,16,1.000000,0.004671,0.000000,1.000000,0.000000,0.006117,0.108814,0.111717,0.00,1.00,-100.000000,0.000000

ModelMetricsBinomial: gbm
** Reported on cross-validation data. **

MSE: 0.07462352394992082
RMSE: 0.2731730659305943
LogLoss: 0.24618672338984696
Mean Per-Class Error: 0.17843755798849514
AUC: 0.8928591310341171
AUCPR: 0.533980637663008
Gini: 0.7857182620682341

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.14659713692750767:

               0      1   Error             Rate
0      0  2120.0  260.0  0.1092   (260.0/2380.0)
1      1    92.0  225.0  0.2902     (92.0/317.0)
2  Total  2212.0  485.0  0.1305   (352.0/2697.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold        value    idx
0                        max f1   0.146597     0.561097  238.0
1                        max f2   0.070334     0.663240  293.0
2                  max f0point5   0.350228     0.564230  158.0
3                  max accuracy   0.362896     0.899147  154.0
4                 max precision   0.984046     1.000000    0.0
5                    max recall   0.004843     1.000000  397.0
6               max specificity   0.984046     1.000000    0.0
7              max absolute_mcc   0.140858     0.504314  241.0
8    max min_per_class_accuracy   0.084432     0.814706  281.0
9   max mean_per_class_accuracy   0.070334     0.821562  293.0
10                      max tns   0.984046  2380.000000    0.0
11                      max fns   0.984046   316.000000    0.0
12                      max fps   0.003765  2380.000000  399.0
13                      max tps   0.004843   317.000000  397.0
14                      max tnr   0.984046     1.000000    0.0
15                      max fnr   0.984046     0.996845    0.0
16                      max fpr   0.003765     1.000000  399.0
17                      max tpr   0.004843     1.000000  397.0

Gains/Lift Table: Avg response rate: 11.75 %, avg score: 10.73 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.010011,0.882050,5.671924,5.671924,0.666667,0.920741,0.666667,0.920741,0.056782,0.056782,467.192429,467.192429
1,,2,0.020022,0.806618,6.932352,6.302138,0.814815,0.843186,0.740741,0.881964,0.069401,0.126183,593.235191,530.213810
2,,3,0.030033,0.734320,5.356817,5.987031,0.629630,0.773344,0.703704,0.845757,0.053628,0.179811,435.681739,498.703120
3,,4,0.040044,0.687125,3.466176,5.356817,0.407407,0.712037,0.629630,0.812327,0.034700,0.214511,246.617596,435.681739
4,,5,0.050056,0.633492,4.726604,5.230775,0.555556,0.662737,0.614815,0.782409,0.047319,0.261830,372.660358,423.077462
5,,6,0.100111,0.357832,4.663582,4.947178,0.548148,0.491371,0.581481,0.636890,0.233438,0.495268,366.358219,394.717841
6,,7,0.150167,0.199472,2.772941,4.222433,0.325926,0.270700,0.496296,0.514827,0.138801,0.634069,177.294076,322.243253
7,,8,0.200222,0.124599,2.205748,3.718261,0.259259,0.156111,0.437037,0.425148,0.110410,0.744479,120.574834,271.826148
8,,9,0.299963,0.064800,1.170230,2.871017,0.137546,0.090587,0.337454,0.313903,0.116719,0.861199,17.022973,187.101730
9,,10,0.400074,0.036385,0.598703,2.302412,0.070370,0.048864,0.270621,0.247582,0.059937,0.921136,-40.129688,130.241227
10,,11,0.500185,0.021910,0.315107,1.904657,0.037037,0.027947,0.223870,0.203623,0.031546,0.952681,-68.489309,90.465656
11,,12,0.599926,0.014985,0.347906,1.645840,0.040892,0.018059,0.193449,0.172772,0.034700,0.987382,-65.209386,64.583959
12,,13,0.700037,0.011342,0.031511,1.414977,0.003704,0.012986,0.166314,0.149921,0.003155,0.990536,-96.848931,41.497688
13,,14,0.799778,0.009019,0.000000,1.238515,0.000000,0.010111,0.145573,0.132485,0.000000,0.990536,-100.000000,23.851476
14,,15,0.899889,0.006986,0.063021,1.107743,0.007407,0.007997,0.130202,0.118636,0.006309,0.996845,-93.697862,10.774294
15,,16,1.000000,0.003311,0.031511,1.000000,0.003704,0.005869,0.117538,0.107347,0.003155,1.000000,-96.848931,0.000000

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,accuracy,0.8883962,0.010976009,0.8962963,0.8759259,0.89239335,0.877551,0.8998145
1,auc,0.89135486,0.013718808,0.8825065,0.9139463,0.88285154,0.89498484,0.8824851
2,aucpr,0.53529197,0.036636017,0.51551026,0.550539,0.59116447,0.5219817,0.4972643
3,err,0.1116038,0.010976009,0.1037037,0.12407407,0.10760668,0.12244898,0.10018553
4,err_count,60.2,5.9329586,56.0,67.0,58.0,66.0,54.0
5,f0point5,0.542779,0.039185718,0.5,0.5183585,0.5984042,0.5319149,0.5652174
6,f1,0.5780642,0.031458717,0.5254237,0.5889571,0.6081081,0.5769231,0.59090906
7,f2,0.6205642,0.045667693,0.5535714,0.6818182,0.6181319,0.6302521,0.61904764
8,lift_top_group,5.716296,1.1483561,6.6666665,7.142857,4.990741,5.363184,4.4180326
9,logloss,0.24619897,0.017002195,0.22549118,0.23387863,0.26544717,0.26051384,0.24566403
10,max_per_class_error,0.345607,0.069638066,0.42592594,0.23809524,0.375,0.3283582,0.36065573
11,mcc,0.521124,0.031118827,0.46980798,0.5395643,0.5460633,0.5139863,0.5361982
12,mean_per_class_accuracy,0.7868502,0.026318261,0.75308645,0.82644504,0.77930945,0.78921074,0.78619933
13,mean_per_class_error,0.21314982,0.026318261,0.24691358,0.17355496,0.22069058,0.21078928,0.21380067
14,mse,0.074627034,0.0059507675,0.06614816,0.07364397,0.079630844,0.080967866,0.07274433
15,pr_auc,0.53529197,0.036636017,0.51551026,0.550539,0.59116447,0.5219817,0.4972643
16,precision,0.5222788,0.047716428,0.484375,0.48,0.59210527,0.505618,0.5492958
17,r2,0.27875036,0.02155491,0.26502046,0.28539547,0.3119667,0.25617048,0.27519873
18,recall,0.65439296,0.069638066,0.5740741,0.7619048,0.625,0.67164177,0.6393443
19,rmse,0.2730033,0.010967407,0.25719285,0.27137423,0.28218937,0.28454852,0.26971158

See the whole table with table.as_data_frame()

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_pr_auc,training_lift,training_classification_error,validation_rmse,validation_logloss,validation_auc,validation_pr_auc,validation_lift,validation_classification_error
0,,2020-05-30 10:36:12,4.209 sec,0.0,0.322060,0.361991,0.500000,0.117538,1.000000,0.882462,0.311528,0.344403,0.500000,0.108814,1.000,0.891186
1,,2020-05-30 10:36:12,4.280 sec,5.0,0.269301,0.255808,0.943307,0.774877,8.507886,0.076010,0.281237,0.277279,0.875049,0.455404,3.676,0.107726
2,,2020-05-30 10:36:12,4.381 sec,10.0,0.237655,0.206721,0.961720,0.839466,8.507886,0.055988,0.268436,0.251187,0.890788,0.473058,4.595,0.088139
3,,2020-05-30 10:36:12,4.508 sec,15.0,0.217664,0.177285,0.967155,0.866487,8.507886,0.050426,0.264064,0.238453,0.900000,0.480261,4.595,0.084875
4,,2020-05-30 10:36:12,4.611 sec,20.0,0.203253,0.156908,0.974775,0.894678,8.507886,0.041898,0.261081,0.230186,0.905006,0.493897,5.514,0.083787
5,,2020-05-30 10:36:13,4.744 sec,25.0,0.189522,0.138623,0.981215,0.917708,8.507886,0.035966,0.262282,0.228961,0.907125,0.486838,3.676,0.088139
6,,2020-05-30 10:36:13,4.848 sec,30.0,0.176878,0.123214,0.986315,0.938388,8.507886,0.031146,0.261987,0.227381,0.906923,0.489786,5.514,0.110990
7,,2020-05-30 10:36:13,4.949 sec,35.0,0.165584,0.111089,0.990124,0.956109,8.507886,0.025584,0.262404,0.227533,0.907961,0.487967,3.676,0.087051
8,,2020-05-30 10:36:13,5.053 sec,40.0,0.155916,0.101573,0.992057,0.967068,8.507886,0.020022,0.262108,0.226239,0.909011,0.498495,2.757,0.093580
9,,2020-05-30 10:36:13,5.110 sec,42.0,0.152111,0.097442,0.993048,0.969855,8.507886,0.019281,0.262768,0.226057,0.911160,0.497008,4.595,0.096844

Variable Importances:

     variable  relative_importance  scaled_importance  percentage
0    duration           300.922302           1.000000    0.321799
1       month           145.885956           0.484796    0.156007
2         job           106.798729           0.354905    0.114208
3    poutcome           100.508408           0.334001    0.107481
4         age            56.186703           0.186715    0.060085
5         day            54.120747           0.179850    0.057875
6     balance            46.184929           0.153478    0.049389
7       pdays            33.132874           0.110104    0.035431
8     contact            21.676632           0.072034    0.023180
9     marital            18.388983           0.061109    0.019665
10    housing            17.317614           0.057548    0.018519
11  education            14.383990           0.047800    0.015382
12   previous             9.674854           0.032151    0.010346
13   campaign             8.728162           0.029005    0.009334
14       loan             1.136615           0.003777    0.001215
15    default             0.078047           0.000259    0.000083

In [8]:
y_pred = model.predict(df)

gbm prediction progress: |████████████████████████████████████████████████| 100%

In [9]:
y_pred

predict,p0,p1
0,0.98118,0.0188199
0,0.911522,0.0884777
0,0.990459,0.00954079
0,0.994017,0.00598349
0,0.989952,0.0100479
1,0.563332,0.436668
0,0.988321,0.011679
0,0.957374,0.0426264
0,0.994767,0.00523295
0,0.953578,0.0464223

In [10]:
print(confusion_matrix(df['target'].as_data_frame()['target'], y_pred['predict'].as_data_frame()['predict']))

[[753  48]
 [ 50  54]]

In [11]:
print(classification_report(df['target'].as_data_frame()['target'], y_pred['predict'].as_data_frame()['predict']))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94       801
           1       0.53      0.52      0.52       104

    accuracy                           0.89       905
   macro avg       0.73      0.73      0.73       905
weighted avg       0.89      0.89      0.89       905